### ISSUE TITLE
some questions and a thanks

### ISSUE THREAD

**Issue by n1ete** [precurse/playbooks#1]
hey there,

first i wanna thank you for sharing these playbooks with the community.... i use them to understand how ansible works and like them so far...
got a question: 
i couldnt figure out exactly for whats the whole "kim" is about in your playbook.... could you give me some hints?
also got some trouble with the samba main task: the  `smbpasswd -a -s` throws me a syntax error.
if i run this command on the samba-vm i get an `WARNING: The "syslog" option is deprecated` and an empty shell cursor...?
i guess it needs some changes because its outdated.
thanks in advance for your time.
greetings from Germany ;)

**Comment by precurse** [comment]
Hello, from Canada! Sorry for the delay in response. I'm glad others are getting use out of them :)

Kim is a nickname for a colo server I have. 

I imagine the `smbpasswd -a -s` command is being run on a different OS than SmartOS? I'm running Samba SmartOS zone, which might be why. I just rebuilt mine with the latest `base-64-lts` version and the playbook ran fine. Let me know if you are and I can take a better look.

Cheers!
